name: Pull request tests
run-name: Pull request tests ${{ github.head_ref }}

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-server:
    name: Server test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM packages
        run: npm ci
      - name: ESlint
        run: npm run eslint
